### ISSUE TITLE
Move topics metadata into YAML files

### ISSUE THREAD

**Issue by abstractalgo** [abstractalgo/rosetta#19]
Instead of using Typescript types, move topics metadata into separate YAML files.

Example of `/public/topics/<topic>/<topic>.yml`:

```yml
label: Some label
description: Some description
categories:
    - Languages
    - Tooling
```
